import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  mainView: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    paddingLeft: 22,
    paddingRight: 20,
  },
  mainView2: {marginTop: 80, height: 580},
  swiper: {height: '100%'},
  firstView: {flex: 1},
  firstImage: {height: 312.78},
  firstText1: {
    color: '#00063D',
    fontSize: 25,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginTop: 35,
  },
  firstText2: {
    color: '#09090C',
    fontSize: 17,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  secondView: {flex: 1},
  secondImage: {height: 357, alignSelf: 'center'},
  secondText1: {
    color: '#00063D',
    fontSize: 25,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginTop: 35,
  },
  secondText2: {
    color: '#4B68FF',
    fontSize: 22,
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
    marginTop: 8,
  },
  thirdView: {flex: 1},
  thirdImage: {height: 326.7, alignSelf: 'center'},
  thirdText1: {
    color: '#00063D',
    fontSize: 25,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginTop: 35,
  },
  thirdText2: {
    color: '#09090C',
    fontSize: 17,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  fourthView: {flex: 1},
  fourthImage: {height: 297.25, alignSelf: 'center'},
  fourthText1: {
    color: '#00063D',
    fontSize: 25,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginTop: 65,
  },
  fourthText2: {
    color: '#09090C',
    fontSize: 17,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginTop: 15,
  },
  fourthText3: {
    color: '#09090C',
    fontSize: 17,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    marginTop: 5,
    marginBottom: 20,
  },
  startButton: {
    backgroundColor: '#4B68FF',
    height: 60,
    marginTop: 20,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontFamily: 'Poppins-Regular',
    fontSize: 17,
  },
  loginText: {
    color: '#484848',
    fontSize: 17,
    fontFamily: 'Poppins-Regular',
    textAlign: 'center',
    marginTop: 19,
  },
});
